### ISSUE TITLE
several lines per task

### ISSUE THREAD

**Issue by gbdomubpkm** [jittopjose/DoToDo#7]
In my opinion, a task should be able to be written and displayed on several lines if necessary (to define the max number, maybe up to 5 or more ?), while being able to make voluntary line feeds: this is not the case it seems to me.
Keeping the first line in bold as the task name.

**Comment by jittopjose** [comment]
I assume you are asking about adding a description field for a task.
In fact i am thinking of making Task list similar to Checklist and Notes with an expander on tapping on task. Then I can add a description input field for task creation and display it on taping each task.

**Comment by jittopjose** [comment]
@gbdomubpkm A new version is published on open-store . Kindly verify and share  your thoughts.

**Comment by gbdomubpkm** [comment]
Thanks for the improvements. A few user observations that came to me if it can help you to improve the app yet.

- why quick task and advanced task ? Why not only 'task' ?

- Currently i see only one line in task description : not several  ?

- Due time : currently  impossible to enter an exact time to the minute (currently 5 minutes in 5 minutes).

- Notes and checklists : currently we don't see if there are notes and checklists :  perhabs indicate the number near the icons ?

- Notification counter: unclear how it works for me.

**Comment by jittopjose** [comment]
@gbdomubpkm 


    **why quick task and advanced task ? Why not only 'task' ? ->**
The idea was to make a create task page with just task name and due date with all other options defaulted. But now I feel like there is no big advantage of keeping such an option. I will reconsider removing it and add an advanced option on task creation for more options.

    **Currently i see only one line in task description : not several ?**
I will make it a text area control to enable entering multiline text in the next version.

    **Due time : currently impossible to enter an exact time to the minute (currently 5 minutes in 5 minutes).**
I did so because in ubports the animations were not so fluid and selecting correct minute value from 60 entries was found very difficult. I will make this as a settings entry to choose between 5 min and 1 min for due time.

    **Notes and checklists : currently we don't see if there are notes and checklists : perhabs indicate the number near the icons ?**
I am thinking of adding a left menu with all the options to make it more visible

    **Notification counter: unclear how it works for me.**
Since the app cannot be run in background and give proper notifications, I created notification area with following logic.
1. The count of unfinished non repeating task of previous day is displayed at the first start of app in a day
2. 3 notifications will be added for a task when it nearing due time..  45 min, 30min and 15 min before the due date. But it will not happen if the app is not opened. 
I guess the notification area need some improvement. I am thinking of better logic to handle it. You can also give your suggestions.

**Comment by gbdomubpkm** [comment]
Thanks for the clarification: 
Indeed, from the user's point of view, the operating principle of notifications should be simple, clear (and if necessary explained in a help section).
For me, maybe the principle of displaying notifications for the unfinished day tasks and the next day but at each start of the application.

**Comment by gbdomubpkm** [comment]
Hi.
I have just noticed that a job description, although it can be written on several lines, seems to be stuck on 40 characters in total. Short...

**Comment by jittopjose** [comment]
@gbdomubpkm Ah..  That was a mistake happened when I was copying from the task name field.. My bad..  I have fixed it in the code..  Will push in the next update.

By the way, the French translation is available now. Is it working fine at your end?

**Comment by gbdomubpkm** [comment]
Ideally, on the pages concerned, the dates should appear in French format.
What is shown in portrait mode on tasks page :
<  Aujourd'hui (dim., sept. 20...   >
<  Demain (lun., sept. 21 2020)  >
<  mar., sept. 22 2020  >
... 

Exact format of the style
<  Aujourd'hui (dim.. 20  sept...    >
<  Demain (lun.. 21 sept.. 2020)  >
<  mardi 22 sept.. 2020  >
...

Ideally, the French format should be used in all the pages concerned as in the page 'Add a new task'.

Apart from that, everything seems fine to me.

**Comment by jittopjose** [comment]
@gbdomubpkm 
Date issue in the task list page is fixed in code. I am working on the date format for note page and create task area. Will try to fix it before next update. Please check the screen below.

![localhost_8100_(Pixel 2)](https://user-images.githubusercontent.com/13288966/93705758-6f790380-fb3d-11ea-8f2b-4591490109c4.png)

**Comment by gbdomubpkm** [comment]
That is ok

**Comment by gbdomubpkm** [comment]
Thank you for dark mode (note french translated : mode nuit).
Number of characters (now > 40) fixed.
French date format not fixed (yet) for note page and for due date of a task.

**Comment by gbdomubpkm** [comment]
For tasks, portrait mode : I think it would be better to have the whole year: 2020 and not 2... . If it's a question of layout, I'd rather maybe abbreviate the word 'aujourd'hui' in aujourd'...
![screenshot20201012_170444731](https://user-images.githubusercontent.com/50362604/95763423-4caabc80-0caf-11eb-873a-523c889b5c1b.png)
